image: atlassian/default-image:3

pipelines:
  branches:
    main:
      - step:
          name: Build Production Omnex Project
          image: node:latest
          script:
            - npm install
            - npm run build
          artifacts:
            - build/**
      - step:
          name: Deploy Production Omnex to S3
          deployment: production
          script:
            - pipe: atlassian/aws-s3-deploy:0.2.4
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                S3_BUCKET: $S3_BUCKET
                ACL: 'public-read'
                LOCAL_PATH: 'build'
    dev:
      - step:
          name: Build Stage Omnex app
          image: node:latest
          script:
            - npm install
            - npm run build
          artifacts:
            - build/**
      - step:
          name: Deploy Staging Omnex to S3
          deployment: staging
          script:
            - pipe: atlassian/aws-s3-deploy:0.2.4
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                S3_BUCKET: $S3_BUCKET
                ACL: 'public-read'
                LOCAL_PATH: 'build'
  custom:
    production:
      - step:
          name: Build Production Omnex Project
          image: node:latest
          script:
            - npm install
            - npm run build
          artifacts:
            - build/**
      - step:
          name: Deploy Production Omnex to S3
          deployment: production
          script:
            - pipe: atlassian/aws-s3-deploy:0.2.4
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                S3_BUCKET: $S3_BUCKET
                ACL: 'public-read'
                LOCAL_PATH: 'build'
    staging:
      - step:
          name: Deploy Staging Omnex to S3
          deployment: staging
          script:
            - pipe: atlassian/aws-s3-deploy:0.2.4
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                S3_BUCKET: $S3_BUCKET
                ACL: 'public-read'
                LOCAL_PATH: '/'
