export const DATA_SOURCE: any = [
  {
    machineName: 'HONOR VTC-15',
    elementName: 'Hydrulic system',
    sensorDescription: 'Oil Temp Outlet',
    sensorID: 'Honor-15_LS',
    operatingRange: '30   -   40',
    thresholdValue: '0 - 40',
    uom: 'Bar',
    interval: '8hr',
    trigger: 'Max',
    criticality: 'Breakdown Defect',
  },
  {
    machineName: 'HONOR VTC-15',
    elementName: 'Hydrulic system',
    sensorDescription: 'Oil Temp Outlet',
    sensorID: 'Honor-15_LS',
    operatingRange: '30   -   40',
    thresholdValue: '0 - 40',
    uom: 'Bar',
    interval: '8hr',
    trigger: 'Max',
    criticality: 'Breakdown Defect',
  },
  {
    machineName: 'HONOR VTC-15',
    elementName: 'Hydrulic system',
    sensorDescription: 'Oil Temp Outlet',
    sensorID: 'Honor-15_LS',
    operatingRange: '30   -   40',
    thresholdValue: '0 - 40',
    uom: 'Bar',
    interval: '8hr',
    trigger: 'Max',
    criticality: 'Breakdown Defect',
  },
  {
    machineName: 'HONOR VTC-15',
    elementName: 'Hydrulic system',
    sensorDescription: 'Oil Temp Outlet',
    sensorID: 'Honor-15_LS',
    operatingRange: '30   -   40',
    thresholdValue: '0 - 40',
    uom: 'Bar',
    interval: '8hr',
    trigger: 'Max',
    criticality: 'Breakdown Defect',
  },
  {
    machineName: 'HONOR VTC-15',
    elementName: 'Hydrulic system',
    sensorDescription: 'Oil Temp Outlet',
    sensorID: 'Honor-15_LS',
    operatingRange: '30   -   40',
    thresholdValue: '0 - 40',
    uom: 'Bar',
    interval: '8hr',
    trigger: 'Max',
    criticality: 'Breakdown Defect',
  },
  {
    machineName: 'HONOR VTC-15',
    elementName: 'Hydrulic system',
    sensorDescription: 'Oil Temp Outlet',
    sensorID: 'Honor-15_LS',
    operatingRange: '30   -   40',
    thresholdValue: '0 - 40',
    uom: 'Bar',
    interval: '8hr',
    trigger: 'Max',
    criticality: 'Breakdown Defect',
  },
  {
    machineName: 'HONOR VTC-15',
    elementName: 'Hydrulic system',
    sensorDescription: 'Oil Temp Outlet',
    sensorID: 'Honor-15_LS',
    operatingRange: '30   -   40',
    thresholdValue: '0 - 40',
    uom: 'Bar',
    interval: '8hr',
    trigger: 'Max',
    criticality: 'Breakdown Defect',
  },
  {
    machineName: 'HONOR VTC-15',
    elementName: 'Hydrulic system',
    sensorDescription: 'Oil Temp Outlet',
    sensorID: 'Honor-15_LS',
    operatingRange: '30   -   40',
    thresholdValue: '0 - 40',
    uom: 'Bar',
    interval: '8hr',
    trigger: 'Max',
    criticality: 'Breakdown Defect',
  },
  {
    machineName: 'HONOR VTC-15',
    elementName: 'Hydrulic system',
    sensorDescription: 'Oil Temp Outlet',
    sensorID: 'Honor-15_LS',
    operatingRange: '30   -   40',
    thresholdValue: '0 - 40',
    uom: 'Bar',
    interval: '8hr',
    trigger: 'Max',
    criticality: 'Breakdown Defect',
  },
  {
    machineName: 'HONOR VTC-15',
    elementName: 'Hydrulic system',
    sensorDescription: 'Oil Temp Outlet',
    sensorID: 'Honor-15_LS',
    operatingRange: '30   -   40',
    thresholdValue: '0 - 40',
    uom: 'Bar',
    interval: '8hr',
    trigger: 'Max',
    criticality: 'Breakdown Defect',
  },
  {
    machineName: 'HONOR VTC-15',
    elementName: 'Hydrulic system',
    sensorDescription: 'Oil Temp Outlet',
    sensorID: 'Honor-15_LS',
    operatingRange: `30   -   40`,
    thresholdValue: '0 - 40',
    uom: 'Bar',
    interval: '8hr',
    trigger: 'Max',
    criticality: 'Breakdown Defect',
  },
];
